version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node   
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200    
    
    ports:
      - 5601:5601
    networks:
      - elastic
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.9.1
    container_name: heartbeat
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volume:
      - ./heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml:ro



volumes:
  data01:
    driver: local
networks:
  elastic:
    external: true
    name: elastic

