version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es01
    environment:
      - discovery.type=single-node   
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    link: 
      - es01:elasticsearch
    ports:
      - 5601:5601

volumes:
  data01:
    driver: local
networks:
  elastic:
    external: true
    name: elastic

