version: '3.7'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.1
    container_name: filebeat
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elastic
networks:
  elastic:
    external: true
    name: elastic