heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - https://smartweld.livnsense.com
    - https://livnsense.myfirewall.co:2001

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '143.110.176.133:9200'
